name: Flutter Desktop Build (Windows + macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Contains Dart 3.5.0
          channel: stable

      - name: Prepare environment
        run: |
          flutter pub cache repair
          flutter clean
          flutter pub get
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            flutter pub run flutter_launcher_icons:main
          fi

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test

      - name: Build release
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            flutter build windows --release
          else
            flutter build macos --release
          fi

      - name: Package artifacts
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cd build/windows/runner/Release
            7z a ../../../../windows-release.zip *
          else
            cd build/macos/Build/Products/Release
            mkdir -p package
            cp -R LifeWeeks.app package/
            hdiutil create -volname "LifeWeeks" -srcfolder package -ov -format UDZO LifeWeeks.dmg
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-release
          path: |
            ${{ runner.os == 'Windows' && 'windows-release.zip' || 'LifeWeeks.dmg' }}
            ${{ runner.os == 'macOS' && 'build/macos/Build/Products/Release/LifeWeeks.app' }}
          retention-days: 7

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-release.zip
            LifeWeeks.dmg
            build/macos/Build/Products/Release/LifeWeeks.app